# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
steps:- 
  - task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMTemplateCiCD'
    subscriptionId: '5761586f-99b8-4741-80df-d6143a7b7bac'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg1505'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/kashave/AzureRmPipelineCICD-repo/main/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName myarmpipeline'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
    addSpnToEnvironment: true

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
